name: jenkins
services:
  jenkins:
    # image: jenkins/jenkins:lts
    build:
      context: ./jenkins
      dockerfile: Containerfile
    environment:
      TZ: "Asia/Tokyo"
    ports:
      - 8081:8080
      - 5000:50000
    volumes:
      - jenkins_home:/var/jenkins_home
      - work:/work
    restart: on-failure
volumes:
  jenkins_home:
  work:
